### ISSUE TITLE
Items duping when shift clicking items out of crafting grid

### ISSUE THREAD

**Issue by JustPlayn10** [Aster0/UnifiedStorage#3]
**Describe the bug**
Shift clicking a crafted item out of the Storage Controller will cause it to be duplicated.

**To Reproduce**
1. Place down Storage Controller
2. Upgrade it with a Crafting Upgrade Card
3. Craft any item inside Storage Controller
4. Shift click output item

**Expected behavior**
Item to be only crafted once, similar to the regular Crafting Table

**Screenshots**
![USDupe](https://github.com/Aster0/UnifiedStorage/assets/52627086/ba66419f-a384-4c72-9f4d-8996dddd782b)

**Minecraft Version (please complete the following information):**
Minecraft 1.20.2 running on server

**Mod Version (please complete the following information):**
unifiedstorage-0.8.3-BETA

**Additional context**
I have too many wooden planks.

**Comment by Aster0** [comment]
Does this always happen? Like the result being left clickable after the crafting table is empty?

EDIT: Oh, I see it’s on a server. Can you help test on a single player environment too and see if it’s an issue? 

I just found some server related crafting sync issues last night and am on my way to fix these issues.

**Comment by Aster0** [comment]
This is fixed in the latest update. 

Additionally, I added a check where it re-confirms the items on the crafting slots before actually processing with the onItemCraft method. This means that no duplications could ever happen even if it's a visual issue, showing that the crafting table is fetching a result, it should not give you the item as the crafting table does not tally.


Appreciate the bug find. Thank you :)
